"""update table

Revision ID: 06cec0a76e7b
Revises: cbe9d00be406
Create Date: 2026-10-09 23:11:08.539065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06cec0a76e7b'
down_revision: Union[str, Sequence[str], None] = 'cbe9d00be406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clicks_link_id_fkey'), 'clicks', type_='foreignkey')
    op.create_foreign_key('clicks_link_id_fkey', 'clicks', 'links', ['link_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('links_owner_id_fkey'), 'links', type_='foreignkey')
    op.create_foreign_key('links_owner_id_fkey', 'links', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('links_owner_id_fkey', 'links', type_='foreignkey')
    op.create_foreign_key(op.f('links_owner_id_fkey'), 'links', 'users', ['owner_id'], ['id'])
    op.drop_constraint('clicks_link_id_fkey', 'clicks', type_='foreignkey')
    op.create_foreign_key(op.f('clicks_link_id_fkey'), 'clicks', 'links', ['link_id'], ['id'])
    # ### end Alembic commands ###
